"""add_git_branch_and_github_pr_url_to_runs

Revision ID: 2429941890d4
Revises: 20260621_0001
Create Date: 2026-06-24 20:15:10.699717
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2429941890d4'
down_revision: Union[str, None] = '20260621_0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('runs', sa.Column('git_branch', sa.String(length=255), nullable=True))
    op.add_column('runs', sa.Column('github_pr_url', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('runs', 'github_pr_url')
    op.drop_column('runs', 'git_branch')
    op.drop_table('projects')
    # ### end Alembic commands ###
