   id = db.Column(db.Integer, primary_key=True)
   username = db.Column(db.String(80), unique=True, nullable=False)
   password = db.Column(db.String(120), nullable=False)
   orders = db.relationship('Order', backref='user', lazy=True)
   id = db.Column(db.Integer, primary_key=True)
   description = db.Column(db.String(200), nullable=False)
   status = db.Column(db.String(50), default='pending')
   user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
   id = db.Column(db.Integer, primary_key=True)
   name = db.Column(db.String(100), nullable=False)
   stock_level = db.Column(db.Integer, default=0)
   id = db.Column(db.Integer, primary_key=True)
   amount = db.Column(db.Float, nullable=False)
   status = db.Column(db.String(50), default='unpaid')
   order_id = db.Column(db.Integer, db.ForeignKey('order.id'), nullable=False)
